// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-aLmqR6PvznUTL5ZYm3gZh5WyUBCqmcI',
    appId: '1:566981057422:web:55f4eb1025a16d04eaa2df',
    messagingSenderId: '566981057422',
    projectId: 'aurify-ee521',
    authDomain: 'aurify-ee521.firebaseapp.com',
    storageBucket: 'aurify-ee521.firebasestorage.app',
    measurementId: 'G-JH9ESYBXMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNaykwrVD5mJw0_tTRQ3LIm1A8Mi91Jbc',
    appId: '1:566981057422:android:b0ab1668b391c966eaa2df',
    messagingSenderId: '566981057422',
    projectId: 'aurify-ee521',
    storageBucket: 'aurify-ee521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXKOijEJTqGdyvCJ53H--hsRCD3I2xUDU',
    appId: '1:566981057422:ios:63d1b17771b08b49eaa2df',
    messagingSenderId: '566981057422',
    projectId: 'aurify-ee521',
    storageBucket: 'aurify-ee521.firebasestorage.app',
    iosBundleId: 'com.example.productExplorer',
  );
}
